### ISSUE TITLE
Queue Management System Enhancements

### ISSUE THREAD

**Issue by bcdevex** [bcgov/queue-management#106]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/cwu/opp-enhancements">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-enhancements">visit the opportunity page</a>. The opportunity closes on <b>Friday, October 26, 2018</b>.</p>

**Comment by molund** [comment]
Has user experience design work already been completed for the requested changes (wireframes, sketches, etc)?

**Comment by gil0109** [comment]
Thank you for your question.  There has not been any UX design work completed for the requested changes.  There are some suggestions on the basic design needed in the opportunity.  That said, we are leaving it to the developer to keep consistent with existing design controls in the application.  We did not want to constrain the developer.

**Comment by freemanjackal** [comment]
i have tried the installation in several pc with ubuntu 16.04 and always get the same error
`
Step 9/10 : RUN /opt/keycloak/setup.sh
 ---> Running in 0c01cd297521
/bin/sh: /opt/keycloak/setup.sh: Permission denied
The command '/bin/sh -c /opt/keycloak/setup.sh' returned a non-zero code: 126
`
any idea? are there some system requirements?

**Comment by gil0109** [comment]
Thank you for your comments @freemanjackal .  For some reason, the executable permissions were stripped out.  

In the local git cloned directory (queue-management/keycloak-local-testserver/) and run this command first:

chmod +x *.sh

Then retry.  Please let me know if that fixes the issue.

Regards,
Karim

**Comment by freemanjackal** [comment]
yes it worked, i was messing with permissions, but your recommendation made the work

**Comment by dhruvio** [comment]
Hi there, I'm not able to "Start a Proposal", as it seems the BC Dev Exchange UI is throwing a run-time exception whenever I click on "Start a Proposal." Is it possible to answer the questions another way?

```
Transition Rejection($id: 4 type: 6, message: The transition errored, detail: TypeError: deniedRoles is undefined)
```

**Comment by dhruvio** [comment]
Regarding my earlier comment, I was able to workaround the bug by using the web inspector to override the `deniedRoles` variable to an empty array (in case anyone else has this problem). I have submitted my proposal.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by gil0109** [comment]
I want to thank everyone who submitted a proposal.  For the unsuccessful candidates, if you wish to have feedback, please don't hesitate to contact me.

**Comment by gil0109** [comment]
Thank you for all your work on this project.  I am closing this Issue as the opportunity is completed.
