### ISSUE TITLE
Room Booking and Exam management enhancements

### ISSUE THREAD

**Issue by bcdevex** [bcgov/queue-management#274]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-room-booking-and-exam-management-enhancements"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-room-booking-and-exam-management-enhancements">visit the opportunity page</a>.
The opportunity closes on <b>Thursday, June 13th, 2019 at 16:00 PDT</b>.</p>

**Comment by pkandathil** [comment]
Hi, Thank you for posting this opportunity. Please, can you elaborate on what "Some in-person work is required" will mean for this project since our team is from Vancouver and this will affect the budget we are working with. Thank you.

**Comment by gil0109** [comment]
@pkandathil Thank you for the great question.  The requirement is there just in case online/remote communication seems to be not accomplishing the correct results.  So we would ask to meet in person and go through the application with both teams to clarify our needs and the potential solution.

**Comment by pkandathil** [comment]
@gil0109 an additional question, in preparation for the proposal would you be able to give me access to the code repository to better understand the project. Thank you.

**Comment by gil0109** [comment]
@pkandathil The code repository https://github.com/bcgov/queue-management.  The room booking portion is a feature within the application that needs to be enabled at the Office level.

I hope that make sense.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by gil0109** [comment]
I want to thank everyone who submitted a proposal. I appreciate the diligent and thoughtful effort that went into creating the proposals.  Please feel free to contact me, if you have any questions or would like some feedback.

**Comment by gil0109** [comment]
Completed Phase 1, 2, 4.  Partial completion of Phase 3.
