### ISSUE TITLE
npm run dev in queue-management/frontend

### ISSUE THREAD

**Issue by yozmag** [bcgov/queue-management#564]
I'm not able to run, no script named run on package.json.
README.md is probably outdated.

**Comment by gil0109** [comment]
Thank you for the info.  You are correct, we have recently added some major enhancements to the project.  I will have our team go through the documentation and update as soon as we can.  My goal is to have a better solution for starting up and running the application for demo purposes.

For now, the new command is: npm run serve

@yozmag   Thank you for your understanding.  I will close this issue once we have fixed the documentation.

**Comment by gil0109** [comment]
We updated to using Dev Containers.  Issue is now resolved.
