### ISSUE TITLE
Service Booking Enhancement to the Queue Management System

### ISSUE THREAD

**Issue by bcdevex** [bcgov/queue-management#71]
<p>This issue has been auto-generated to facilitate questions about <a href="https://bcdevexchange.org/opportunities/swu/opp-service-booking-enhancement-to-the-queue-management-system">a paid opportunity</a> that has just been posted on the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/swu/opp-service-booking-enhancement-to-the-queue-management-system">visit the opportunity page</a>. The opportunity closes on <b>Monday, October 1, 2018</b>.</p>

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by gil0109** [comment]
Thank you for all your work on this project.
